package com.madson.logdeestudos.service;

import java.util.Arrays;
import java.util.List;

import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import com.madson.logdeestudos.model.Assunto;
import com.madson.logdeestudos.model.Materia;
import com.madson.logdeestudos.repository.AssuntoRepository;
import com.madson.logdeestudos.repository.MateriaRepository;

@Component
public class CargaInicial implements CommandLineRunner {

    private final MateriaRepository materiaRepository;
    private final AssuntoRepository assuntoRepository;

    public CargaInicial(MateriaRepository materiaRepository, AssuntoRepository assuntoRepository) {
        this.materiaRepository = materiaRepository;
        this.assuntoRepository = assuntoRepository;
    }

    @Override
    public void run(String... args) throws Exception {
        
        // Só executa se o banco estiver vazio
        if (materiaRepository.count() == 0) {
            
            // --- 1. CADASTRO DAS DISCIPLINAS ---
            Materia mat = new Materia("Matemática");
            Materia port = new Materia("Português");
            Materia hist = new Materia("História");
            Materia geo = new Materia("Geografia");
            Materia fis = new Materia("Física");
            Materia qui = new Materia("Química");
            Materia bio = new Materia("Biologia");
            Materia ing = new Materia("Inglês");
            Materia fil = new Materia("Filosofia");
            Materia soc = new Materia("Sociologia");
            Materia lit = new Materia("Literatura");
            Materia art = new Materia("Artes");
            Materia red = new Materia("Redação");

            materiaRepository.saveAll(Arrays.asList(mat, port, hist, geo, fis, qui, bio, ing, fil, soc, lit, art, red));

            // --- 2. LISTA ULTRA DETALHADA (NÍVEL HARDCORE) ---
            List<Assunto> listaAssuntos = Arrays.asList(
                
                // ================= MATEMÁTICA =================
                // Aritmética e Álgebra Básica
                new Assunto("Operações Básicas e Expressões Numéricas", mat),
                new Assunto("Critérios de Divisibilidade", mat),
                new Assunto("MMC e MDC", mat),
                new Assunto("Frações e Dízimas Periódicas", mat),
                new Assunto("Potenciação e Radiciação (Propriedades)", mat),
                new Assunto("Racionalização de Denominadores", mat),
                new Assunto("Produtos Notáveis e Fatoração Algébrica", mat),
                new Assunto("Razão, Proporção e Escalas", mat),
                new Assunto("Grandezas Diretamente e Inversamente Proporcionais", mat),
                new Assunto("Regra de Três Simples e Composta", mat),
                new Assunto("Porcentagem: Aumentos e Descontos", mat),
                new Assunto("Matemática Financeira: Juros Simples", mat),
                new Assunto("Matemática Financeira: Juros Compostos e Amortização", mat),
                // Conjuntos e Funções
                new Assunto("Teoria dos Conjuntos e Diagrama de Venn", mat),
                new Assunto("Conjuntos Numéricos (N, Z, Q, I, R)", mat),
                new Assunto("Intervalos Reais", mat),
                new Assunto("Introdução às Funções (Domínio, Imagem, Contradomínio)", mat),
                new Assunto("Função Injetora, Sobrejetora e Bijetora", mat),
                new Assunto("Função Composta e Função Inversa", mat),
                new Assunto("Função de 1º Grau (Afim): Gráfico e Raiz", mat),
                new Assunto("Função de 1º Grau: Estudo do Sinal e Inequações", mat),
                new Assunto("Função de 2º Grau (Quadrática): Raízes e Bhaskara", mat),
                new Assunto("Função de 2º Grau: Vértice, Máximos e Mínimos", mat),
                new Assunto("Função de 2º Grau: Gráfico e Inequações", mat),
                new Assunto("Inequações Produto e Quociente", mat),
                new Assunto("Função Modular: Equações e Inequações", mat),
                new Assunto("Função Modular: Gráficos", mat),
                new Assunto("Função Exponencial: Equações e Gráficos", mat),
                new Assunto("Função Exponencial: Inequações", mat),
                new Assunto("Logaritmos: Definição e Propriedades", mat),
                new Assunto("Função Logarítmica: Equações e Gráficos", mat),
                new Assunto("Função Logarítmica: Inequações e Mantissa", mat),
                // Sequências e Matrizes
                new Assunto("Sequências Numéricas e Lei de Formação", mat),
                new Assunto("Progressão Aritmética (PA): Termo Geral", mat),
                new Assunto("Progressão Aritmética (PA): Soma e Propriedades", mat),
                new Assunto("Progressão Geométrica (PG): Termo Geral", mat),
                new Assunto("Progressão Geométrica (PG): Soma Finita e Infinita", mat),
                new Assunto("Matrizes: Tipos e Operações", mat),
                new Assunto("Matrizes: Multiplicação e Inversa", mat),
                new Assunto("Determinantes: Regra de Sarrus (2x2, 3x3)", mat),
                new Assunto("Determinantes: Teorema de Laplace e Chió", mat),
                new Assunto("Determinantes: Propriedades e Vandermonde", mat),
                new Assunto("Sistemas Lineares: Regra de Cramer", mat),
                new Assunto("Sistemas Lineares: Escalonamento e Discussão", mat),
                new Assunto("Sistemas Lineares Homogêneos", mat),
                // Combinatória e Probabilidade
                new Assunto("Princípio Fundamental da Contagem (PFC)", mat),
                new Assunto("Fatorial e Permutação Simples", mat),
                new Assunto("Permutação com Repetição e Circular", mat),
                new Assunto("Arranjo Simples", mat),
                new Assunto("Combinação Simples", mat),
                new Assunto("Combinação com Repetição e Lemas de Kaplansky", mat),
                new Assunto("Binômio de Newton: Termo Geral e Triângulo de Pascal", mat),
                new Assunto("Polinômio de Leibniz", mat),
                new Assunto("Probabilidade: Definição e Espaço Amostral", mat),
                new Assunto("Probabilidade da União e Eventos Complementares", mat),
                new Assunto("Probabilidade Condicional e Multiplicação", mat),
                new Assunto("Probabilidade: Distribuição Binomial", mat),
                new Assunto("Estatística: Média (Simples e Ponderada)", mat),
                new Assunto("Estatística: Moda e Mediana", mat),
                new Assunto("Estatística: Desvio Padrão e Variância", mat),
                // Geometria Plana
                new Assunto("Conceitos Primitivos e Ângulos", mat),
                new Assunto("Triângulos: Classificação e Pontos Notáveis", mat),
                new Assunto("Triângulos: Congruência e Semelhança", mat),
                new Assunto("Teorema de Tales", mat),
                new Assunto("Relações Métricas no Triângulo Retângulo", mat),
                new Assunto("Relações Métricas no Triângulo Qualquer", mat),
                new Assunto("Polígonos: Diagonais e Ângulos", mat),
                new Assunto("Quadriláteros Notáveis (Trapézio, Losango...)", mat),
                new Assunto("Círculo e Circunferência: Ângulos e Arcos", mat),
                new Assunto("Círculo: Potência de Ponto", mat),
                new Assunto("Áreas de Figuras Planas: Triângulos", mat),
                new Assunto("Áreas de Figuras Planas: Quadriláteros", mat),
                new Assunto("Áreas de Figuras Planas: Círculos e Setores", mat),
                // Geometria Espacial
                new Assunto("Geometria de Posição: Ponto, Reta e Plano", mat),
                new Assunto("Poliedros de Platão e Euler", mat),
                new Assunto("Prismas e Paralelepípedos (Área e Volume)", mat),
                new Assunto("Cubo (Área e Volume)", mat),
                new Assunto("Pirâmides e Troncos", mat),
                new Assunto("Cilindros (Área e Volume)", mat),
                new Assunto("Cones e Troncos", mat),
                new Assunto("Esferas e Partes da Esfera", mat),
                new Assunto("Sólidos de Revolução e Pappus-Guldin", mat),
                new Assunto("Inscrição e Circunscrição de Sólidos", mat),
                // Geometria Analítica
                new Assunto("GA: Ponto, Distância e Ponto Médio", mat),
                new Assunto("GA: Estudo da Reta (Equações Geral e Reduzida)", mat),
                new Assunto("GA: Posição Relativa entre Retas", mat),
                new Assunto("GA: Distância de Ponto a Reta", mat),
                new Assunto("GA: Estudo da Circunferência", mat),
                new Assunto("GA: Posição Relativa Reta-Circunferência", mat),
                new Assunto("GA: Cônicas - Elipse", mat),
                new Assunto("GA: Cônicas - Hipérbole", mat),
                new Assunto("GA: Cônicas - Parábola", mat),
                new Assunto("GA: Rotação e Translação de Eixos", mat),
                // Trigonometria
                new Assunto("Trigonometria no Triângulo Retângulo", mat),
                new Assunto("Ciclo Trigonométrico e Arcos Côngruos", mat),
                new Assunto("Funções Seno e Cosseno (Gráficos)", mat),
                new Assunto("Funções Tangente, Cotangente, Secante e Cossecante", mat),
                new Assunto("Relações Fundamentais", mat),
                new Assunto("Transformações: Soma e Diferença de Arcos", mat),
                new Assunto("Arco Duplo e Arco Metade", mat),
                new Assunto("Transformação em Produto (Prostaférese)", mat),
                new Assunto("Equações Trigonométricas", mat),
                new Assunto("Inequações Trigonométricas", mat),
                new Assunto("Funções Trigonométricas Inversas (Arcsen...)", mat),
                // Números Complexos e Polinômios
                new Assunto("Complexos: Forma Algébrica e Potências de i", mat),
                new Assunto("Complexos: Forma Trigonométrica (Polar)", mat),
                new Assunto("Complexos: Operações na Forma Polar", mat),
                new Assunto("Complexos: Raízes Enésimas e Interpretação Geométrica", mat),
                new Assunto("Polinômios: Grau, Valor Numérico e Identidade", mat),
                new Assunto("Polinômios: Divisão (Chave e Briot-Ruffini)", mat),
                new Assunto("Polinômios: Teorema do Resto e D'Alembert", mat),
                new Assunto("Equações Algébricas: Teorema Fundamental", mat),
                new Assunto("Relações de Girard (Soma e Produto)", mat),
                new Assunto("Raízes Complexas e Racionais", mat),
                new Assunto("Equações Recíprocas", mat),
                // Cálculo e Vetores (Nível Superior/Militar)
                new Assunto("Vetores no R2 e R3 (Soma e Subtração)", mat),
                new Assunto("Produto Escalar e Vetorial", mat),
                new Assunto("Produto Misto", mat),
                new Assunto("Limites: Noção Intuitiva e Propriedades", mat),
                new Assunto("Limites Fundamentais", mat),
                new Assunto("Derivadas: Definição e Regras Básicas", mat),
                new Assunto("Derivadas: Regra da Cadeia e Aplicações (Máx/Mín)", mat),
                new Assunto("Integrais: Indefinidas e Definidas (Áreas)", mat),

                // ================= FÍSICA =================
                // Cinemática
                new Assunto("Grandezas Físicas e Sistema Internacional", fis),
                new Assunto("Cinemática Escalar: Velocidade Média", fis),
                new Assunto("Movimento Uniforme (MU) e Gráficos", fis),
                new Assunto("Movimento Uniformemente Variado (MUV) e Torricelli", fis),
                new Assunto("Gráficos do MUV", fis),
                new Assunto("Queda Livre e Lançamento Vertical", fis),
                new Assunto("Vetores: Soma, Subtração e Decomposição", fis),
                new Assunto("Cinemática Vetorial", fis),
                new Assunto("Lançamento Horizontal", fis),
                new Assunto("Lançamento Oblíquo", fis),
                new Assunto("Movimento Circular Uniforme (MCU): Período/Frequência", fis),
                new Assunto("Movimento Circular Uniformemente Variado (MCUV)", fis),
                new Assunto("Acoplamento de Polias", fis),
                // Dinâmica
                new Assunto("1ª Lei de Newton (Inércia)", fis),
                new Assunto("2ª Lei de Newton (Fundamental) e 3ª Lei (Ação e Reação)", fis),
                new Assunto("Força Peso e Normal", fis),
                new Assunto("Força de Tração e Polias", fis),
                new Assunto("Força de Atrito (Estático e Cinético)", fis),
                new Assunto("Plano Inclinado (Com e Sem Atrito)", fis),
                new Assunto("Força Elástica (Lei de Hooke)", fis),
                new Assunto("Força Centrípeta e Tangencial", fis),
                new Assunto("Pêndulo Cônico e Globo da Morte", fis),
                new Assunto("Trabalho de uma Força Constante", fis),
                new Assunto("Trabalho de Força Variável e Potência", fis),
                new Assunto("Energia Cinética e Teorema da Energia Cinética", fis),
                new Assunto("Energia Potencial (Gravitacional e Elástica)", fis),
                new Assunto("Conservação da Energia Mecânica", fis),
                new Assunto("Sistemas Dissipativos", fis),
                new Assunto("Impulso e Teorema do Impulso", fis),
                new Assunto("Quantidade de Movimento e Conservação", fis),
                new Assunto("Choques e Colisões (Elástico/Inelástico)", fis),
                new Assunto("Centro de Massa", fis),
                // Estática e Gravitação
                new Assunto("Estática do Ponto Material", fis),
                new Assunto("Estática do Corpo Extenso (Torque/Momento)", fis),
                new Assunto("Alavancas e Máquinas Simples", fis),
                new Assunto("Gravitação: Leis de Kepler", fis),
                new Assunto("Gravitação: Lei da Gravitação Universal", fis),
                new Assunto("Campo Gravitacional e Velocidade de Escape", fis),
                // Hidrostática
                new Assunto("Densidade e Pressão", fis),
                new Assunto("Teorema de Stevin e Vasos Comunicantes", fis),
                new Assunto("Teorema de Pascal (Prensas Hidráulicas)", fis),
                new Assunto("Teorema de Arquimedes (Empuxo)", fis),
                new Assunto("Hidrodinâmica: Vazão e Equação da Continuidade", fis),
                new Assunto("Hidrodinâmica: Equação de Bernoulli", fis),
                // Termologia
                new Assunto("Termometria: Escalas (Celsius, Fahrenheit, Kelvin)", fis),
                new Assunto("Dilatação Térmica (Linear, Superficial, Volumétrica)", fis),
                new Assunto("Dilatação dos Líquidos", fis),
                new Assunto("Calorimetria: Calor Sensível e Latente", fis),
                new Assunto("Trocas de Calor e Equilíbrio Térmico", fis),
                new Assunto("Propagação do Calor (Condução, Convecção, Irradiação)", fis),
                new Assunto("Estudo dos Gases: Transformações Gasosas", fis),
                new Assunto("Equação de Clapeyron", fis),
                new Assunto("1ª Lei da Termodinâmica", fis),
                new Assunto("Trabalho em Transformações Gasosas", fis),
                new Assunto("2ª Lei da Termodinâmica e Ciclo de Carnot", fis),
                new Assunto("Ciclos Termodinâmicos e Entropia", fis),
                // Óptica
                new Assunto("Princípios da Óptica Geométrica", fis),
                new Assunto("Reflexão e Espelhos Planos", fis),
                new Assunto("Espelhos Esféricos (Côncavo e Convexo)", fis),
                new Assunto("Refração da Luz e Lei de Snell", fis),
                new Assunto("Reflexão Total e Dioptro Plano", fis),
                new Assunto("Lentes Esféricas (Convergente e Divergente)", fis),
                new Assunto("Vergência e Equação dos Fabricantes de Lentes", fis),
                new Assunto("Instrumentos Ópticos (Microscópio, Telescópio)", fis),
                new Assunto("Óptica da Visão e Defeitos", fis),
                // Ondulatória e MHS
                new Assunto("MHS: Equações e Energia", fis),
                new Assunto("Pêndulo Simples e Sistema Massa-Mola", fis),
                new Assunto("Classificação das Ondas", fis),
                new Assunto("Equação Fundamental da Ondulatória", fis),
                new Assunto("Fenômenos Ondulatórios (Reflexão, Refração, Difração)", fis),
                new Assunto("Interferência e Polarização", fis),
                new Assunto("Acústica: Qualidades Fisiológicas do Som", fis),
                new Assunto("Cordas Vibrantes e Tubos Sonoros", fis),
                new Assunto("Efeito Doppler", fis),
                // Eletricidade e Magnetismo
                new Assunto("Carga Elétrica e Eletrização", fis),
                new Assunto("Lei de Coulomb (Força Elétrica)", fis),
                new Assunto("Campo Elétrico e Linhas de Força", fis),
                new Assunto("Potencial Elétrico e Trabalho", fis),
                new Assunto("Superfícies Equipotenciais", fis),
                new Assunto("Condutores em Equilíbrio Eletrostático", fis),
                new Assunto("Corrente Elétrica e Leis de Ohm", fis),
                new Assunto("Resistores e Associação (Série/Paralelo)", fis),
                new Assunto("Curto-Circuito e Ponte de Wheatstone", fis),
                new Assunto("Geradores e Receptores Reais", fis),
                new Assunto("Leis de Kirchhoff", fis),
                new Assunto("Capacitores e Associação", fis),
                new Assunto("Campo Magnético (Ímãs e Terra)", fis),
                new Assunto("Campo gerado por Corrente (Fio, Espira, Solenoide)", fis),
                new Assunto("Força Magnética sobre Cargas", fis),
                new Assunto("Força Magnética sobre Fios", fis),
                new Assunto("Indução Eletromagnética e Lei de Faraday", fis),
                new Assunto("Lei de Lenz e Transformadores", fis),
                new Assunto("Corrente Alternada (Noções Básicas)", fis),
                // Física Moderna
                new Assunto("Relatividade Restrita: Dilatação do Tempo", fis),
                new Assunto("Relatividade: Contração do Espaço", fis),
                new Assunto("Efeito Fotoelétrico", fis),
                new Assunto("Modelos Atômicos (Bohr) e Dualidade Onda-Partícula", fis),
                new Assunto("Radioatividade (Decaimento)", fis),

                // ================= QUÍMICA =================
                // Química Geral
                new Assunto("Matéria, Energia e Estados Físicos", qui),
                new Assunto("Substâncias, Misturas e Gráficos de Mudança de Fase", qui),
                new Assunto("Métodos de Separação de Misturas", qui),
                new Assunto("Modelos Atômicos: Dalton, Thomson, Rutherford, Bohr", qui),
                new Assunto("Estrutura Atômica: Prótons, Elétrons, Nêutrons, Isótopos", qui),
                new Assunto("Distribuição Eletrônica (Linus Pauling)", qui),
                new Assunto("Números Quânticos", qui),
                new Assunto("Tabela Periódica: Histórico e Organização", qui),
                new Assunto("Propriedades Periódicas (Raio, Eletronegatividade...)", qui),
                new Assunto("Regra do Octeto e Ligação Iônica", qui),
                new Assunto("Ligação Covalente (Normal e Dativa)", qui),
                new Assunto("Ligação Metálica e Ligas", qui),
                new Assunto("Geometria Molecular (VSEPR)", qui),
                new Assunto("Polaridade das Ligações e Moléculas", qui),
                new Assunto("Forças Intermoleculares (Van der Waals, Hidrogênio)", qui),
                new Assunto("Número de Oxidação (Nox)", qui),
                // Química Inorgânica
                new Assunto("Teoria de Arrhenius e Dissociação/Ionização", qui),
                new Assunto("Ácidos: Classificação e Nomenclatura", qui),
                new Assunto("Bases: Classificação e Nomenclatura", qui),
                new Assunto("Sais: Reações de Neutralização e Nomenclatura", qui),
                new Assunto("Óxidos: Classificação e Nomenclatura", qui),
                new Assunto("Reações Químicas: Classificação (Síntese, Decomposição...)", qui),
                new Assunto("Reações de Dupla Troca e Condições de Ocorrência", qui),
                new Assunto("Reações de Oxirredução e Balanceamento Redox", qui),
                // Físico-Química (Estequiometria e Soluções)
                new Assunto("Massas Atômicas e Moleculares", qui),
                new Assunto("Constante de Avogadro e Conceito de Mol", qui),
                new Assunto("Cálculo de Fórmulas (Mínima, Percentual, Molecular)", qui),
                new Assunto("Leis Ponderais (Lavoisier, Proust)", qui),
                new Assunto("Estequiometria Simples", qui),
                new Assunto("Estequiometria: Excesso e Limitante", qui),
                new Assunto("Estequiometria: Pureza e Rendimento", qui),
                new Assunto("Estudo dos Gases (Equação Geral)", qui),
                new Assunto("Misturas Gasosas e Pressão Parcial", qui),
                new Assunto("Soluções: Classificação e Curvas de Solubilidade", qui),
                new Assunto("Unidades de Concentração (g/L, mol/L, %)", qui),
                new Assunto("Diluição e Mistura de Soluções", qui),
                new Assunto("Titulometria", qui),
                new Assunto("Propriedades Coligativas: Tonoscopia e Ebulioscopia", qui),
                new Assunto("Propriedades Coligativas: Crioscopia e Osmoscopia", qui),
                new Assunto("Fator de Van't Hoff", qui),
                // Físico-Química (Energia e Cinética)
                new Assunto("Termoquímica: Exotérmico e Endotérmico", qui),
                new Assunto("Entalpia e Gráficos", qui),
                new Assunto("Lei de Hess", qui),
                new Assunto("Energia de Ligação e Entalpia de Formação", qui),
                new Assunto("Entropia e Energia Livre de Gibbs", qui),
                new Assunto("Cinética Química: Velocidade Média", qui),
                new Assunto("Teoria das Colisões e Energia de Ativação", qui),
                new Assunto("Fatores que alteram a Velocidade", qui),
                new Assunto("Lei da Velocidade (Ordem da Reação)", qui),
                // Equilíbrio Químico
                new Assunto("Conceito de Equilíbrio e Constante (Kc e Kp)", qui),
                new Assunto("Deslocamento de Equilíbrio (Le Chatelier)", qui),
                new Assunto("Equilíbrio Iônico: Ki e Lei de Ostwald", qui),
                new Assunto("Potencial Hidrogeniônico (pH e pOH)", qui),
                new Assunto("Hidrólise Salina", qui),
                new Assunto("Solução Tampão", qui),
                new Assunto("Produto de Solubilidade (Kps)", qui),
                // Eletroquímica
                new Assunto("Pilhas Eletroquímicas (Daniell)", qui),
                new Assunto("Potencial Padrão de Redução e ddp", qui),
                new Assunto("Corrosão e Proteção de Metais", qui),
                new Assunto("Eletrólise Ígnea", qui),
                new Assunto("Eletrólise Aquosa", qui),
                new Assunto("Leis de Faraday e Estequiometria da Eletrólise", qui),
                new Assunto("Radioatividade: Emissões Alfa, Beta, Gama", qui),
                new Assunto("Leis da Radioatividade e Meia-Vida", qui),
                new Assunto("Fissão e Fusão Nuclear", qui),
                // Química Orgânica
                new Assunto("Histórico e Postulados de Kekulé", qui),
                new Assunto("Classificação do Carbono e Cadeias", qui),
                new Assunto("Hidrocarbonetos: Alcanos, Alcenos, Alcinos", qui),
                new Assunto("Hidrocarbonetos: Ciclanos e Aromáticos", qui),
                new Assunto("Petróleo e Combustíveis Fósseis", qui),
                new Assunto("Funções Oxigenadas: Álcool, Fenol, Enol", qui),
                new Assunto("Funções Oxigenadas: Aldeído e Cetona", qui),
                new Assunto("Funções Oxigenadas: Ácido Carboxílico e Éster", qui),
                new Assunto("Funções Oxigenadas: Éter e Anidrido", qui),
                new Assunto("Funções Nitrogenadas: Amina, Amida, Nitrila", qui),
                new Assunto("Outras Funções: Haletos, Tiois, Compostos de Grignard", qui),
                new Assunto("Séries Orgânicas e Propriedades Físicas", qui),
                new Assunto("Isomeria Plana (Cadeia, Posição, Função...)", qui),
                new Assunto("Isomeria Geométrica (Cis-Trans / E-Z)", qui),
                new Assunto("Isomeria Óptica (Quiralidade)", qui),
                new Assunto("Reações Orgânicas: Adição e Substituição", qui),
                new Assunto("Reações Orgânicas: Eliminação", qui),
                new Assunto("Reações de Oxidação (Energética, Branda, Ozonólise)", qui),
                new Assunto("Reações de Esterificação e Saponificação", qui),
                new Assunto("Polímeros Sintéticos e Naturais", qui),
                new Assunto("Química Ambiental (Chuva Ácida, Efeito Estufa, Camada de Ozônio)", qui),

                // ================= PORTUGUÊS =================
                // Fonética e Ortografia
                new Assunto("Fonemas e Letras", port),
                new Assunto("Encontros Vocálicos e Consonantais", port),
                new Assunto("Dígrafos e Divisão Silábica", port),
                new Assunto("Acentuação Gráfica (Regras Gerais e Especiais)", port),
                new Assunto("Uso do Hífen (Novo Acordo)", port),
                new Assunto("Ortografia: Uso de S/Z/X/Ch/G/J", port),
                new Assunto("Emprego dos Porquês", port),
                // Morfologia
                new Assunto("Estrutura das Palavras (Radical, Afixos)", port),
                new Assunto("Processos de Formação (Derivação/Composição)", port),
                new Assunto("Substantivos: Classificação e Flexão", port),
                new Assunto("Artigos e Numerais", port),
                new Assunto("Adjetivos e Locuções Adjetivas", port),
                new Assunto("Pronomes Pessoais, Possessivos e Demonstrativos", port),
                new Assunto("Pronomes Relativos, Indefinidos e Interrogativos", port),
                new Assunto("Colocação Pronominal (Próclise, Ênclise, Mesóclise)", port),
                new Assunto("Verbos: Modos, Tempos e Conjugações", port),
                new Assunto("Verbos: Vozes Verbais e Classificação", port),
                new Assunto("Verbos Irregulares e Defectivos", port),
                new Assunto("Advérbios e Locuções Adverbiais", port),
                new Assunto("Preposições e Conjunções (Coordenativas/Subordinativas)", port),
                new Assunto("Interjeições e Palavras Denotativas", port),
                // Sintaxe
                new Assunto("Frase, Oração e Período", port),
                new Assunto("Sujeito: Tipos e Identificação", port),
                new Assunto("Predicado (Verbal, Nominal, Verbo-Nominal)", port),
                new Assunto("Termos Integrantes: Objetos Direto e Indireto", port),
                new Assunto("Complemento Nominal vs Adjunto Adnominal", port),
                new Assunto("Agente da Passiva", port),
                new Assunto("Termos Acessórios: Adjunto Adverbial e Aposto", port),
                new Assunto("Vocativo", port),
                new Assunto("Período Composto por Coordenação", port),
                new Assunto("Orações Subordinadas Substantivas", port),
                new Assunto("Orações Subordinadas Adjetivas", port),
                new Assunto("Orações Subordinadas Adverbiais", port),
                new Assunto("Orações Reduzidas", port),
                // Sintaxe de Concordância e Regência
                new Assunto("Concordância Nominal (Regras Gerais e Casos)", port),
                new Assunto("Concordância Verbal (Sujeito Simples e Composto)", port),
                new Assunto("Concordância Verbal (Casos Especiais: Ser, Haver...)", port),
                new Assunto("Regência Nominal", port),
                new Assunto("Regência Verbal (Principais Verbos)", port),
                new Assunto("Crase: Casos Obrigatórios", port),
                new Assunto("Crase: Casos Proibidos e Facultativos", port),
                new Assunto("Pontuação: Uso da Vírgula", port),
                new Assunto("Pontuação: Outros Sinais", port),
                // Semântica e Estilística
                new Assunto("Significação: Sinônimos, Antônimos, Homônimos", port),
                new Assunto("Polisemia e Ambiguidade", port),
                new Assunto("Denotação e Conotação", port),
                new Assunto("Figuras de Palavras (Metáfora, Metonímia...)", port),
                new Assunto("Figuras de Pensamento (Ironia, Antítese...)", port),
                new Assunto("Figuras de Sintaxe (Elipse, Hipérbato...)", port),
                new Assunto("Vícios de Linguagem (Barbarismo, Solecismo...)", port),
                new Assunto("Funções da Linguagem (Fática, Poética...)", port),
                new Assunto("Variação Linguística", port),
                new Assunto("Interpretação de Textos: Tipologia e Gêneros", port),
                new Assunto("Coesão e Coerência Textual", port),

                // ================= LITERATURA =================
                new Assunto("Teoria Literária: Texto Literário e Não-Literário", lit),
                new Assunto("Gêneros Literários: Lírico, Épico, Dramático", lit),
                new Assunto("Elementos da Narrativa e Poesia (Métrica/Rima)", lit),
                new Assunto("Trovadorismo: Cantigas e Contexto", lit),
                new Assunto("Humanismo: Gil Vicente e Teatro", lit),
                new Assunto("Classicismo: Camões e Os Lusíadas", lit),
                new Assunto("Quinhentismo Brasileiro: Cartas e Jesuítas", lit),
                new Assunto("Barroco: Gregório de Matos e Padre Vieira", lit),
                new Assunto("Arcadismo: Bocage e Cláudio Manuel da Costa", lit),
                new Assunto("Romantismo Poesia: 1ª Geração (Indianista)", lit),
                new Assunto("Romantismo Poesia: 2ª Geração (Mal do Século)", lit),
                new Assunto("Romantismo Poesia: 3ª Geração (Condoreira)", lit),
                new Assunto("Romantismo Prosa: Urbano, Indianista, Regional", lit),
                new Assunto("Realismo: Machado de Assis", lit),
                new Assunto("Naturalismo: O Cortiço e Aluísio Azevedo", lit),
                new Assunto("Parnasianismo: Tríade Parnasiana", lit),
                new Assunto("Simbolismo: Cruz e Sousa e Alphonsus de Guimaraens", lit),
                new Assunto("Pré-Modernismo: Euclides da Cunha (Os Sertões)", lit),
                new Assunto("Pré-Modernismo: Lima Barreto e Monteiro Lobato", lit),
                new Assunto("Vanguardas Europeias (Futurismo, Cubismo, Dadaísmo...)", lit),
                new Assunto("Semana de Arte Moderna de 1922", lit),
                new Assunto("Modernismo 1ª Fase: Mário e Oswald de Andrade", lit),
                new Assunto("Modernismo 2ª Fase Poesia: Drummond e Vinicius", lit),
                new Assunto("Modernismo 2ª Fase Prosa: Graciliano Ramos e Jorge Amado", lit),
                new Assunto("Modernismo 3ª Fase: João Cabral e Guimarães Rosa", lit),
                new Assunto("Clarice Lispector e a Prosa Intimista", lit),
                new Assunto("Concretismo e Poesia Marginal (Anos 70)", lit),
                new Assunto("Literatura Contemporânea Brasileira", lit),
                new Assunto("Literatura Africana de Língua Portuguesa", lit),
                
                // ================= REDAÇÃO =================
                new Assunto("Estrutura da Dissertação-Argumentativa", red),
                new Assunto("Leitura e Interpretação da Coletânea", red),
                new Assunto("Tese e Projeto de Texto", red),
                new Assunto("Tipos de Argumentos (Autoridade, Dados, Histórico)", red),
                new Assunto("Introdução: Estratégias de Abertura", red),
                new Assunto("Desenvolvimento: O Parágrafo Padrão", red),
                new Assunto("Conclusão: Síntese e Fechamento", red),
                new Assunto("Conclusão ENEM: Proposta de Intervenção Completa", red),
                new Assunto("Coesão Textual: Operadores Argumentativos", red),
                new Assunto("Coerência e Progressão Textual", red),
                new Assunto("Citações Filosóficas e Sociológicas", red),
                new Assunto("Alusões Históricas e Literárias", red),
                new Assunto("Critérios de Correção ENEM (Competências 1 a 5)", red),
                new Assunto("Gêneros: Carta Argumentativa", red),
                new Assunto("Gêneros: Artigo de Opinião", red),
                new Assunto("Gêneros: Crônica e Conto", red),
                new Assunto("Gêneros: Resumo e Resenha", red),
                new Assunto("Redação Modelo Banca Militar (Tema Livre)", red),

                // ================= ARTES =================
                new Assunto("Arte na Pré-História (Rupestre)", art),
                new Assunto("Arte no Egito Antigo", art),
                new Assunto("Arte Greco-Romana (Clássica)", art),
                new Assunto("Arte Medieval (Bizantina, Românica, Gótica)", art),
                new Assunto("Renascimento Cultural (Itália e Norte)", art),
                new Assunto("Barroco e Rococó", art),
                new Assunto("Neoclassicismo e Romantismo", art),
                new Assunto("Realismo e Impressionismo", art),
                new Assunto("Pós-Impressionismo (Van Gogh, Cézanne)", art),
                new Assunto("Vanguardas Europeias nas Artes Plásticas", art),
                new Assunto("Arte Moderna no Brasil (Anita Malfatti, Tarsila)", art),
                new Assunto("Arte Contemporânea: Pop Art e Op Art", art),
                new Assunto("Arte Contemporânea: Instalação e Performance", art),
                new Assunto("Fotografia e Cinema", art),
                new Assunto("História da Música Erudita e Popular", art),
                new Assunto("Elementos da Linguagem Visual", art),
                new Assunto("Patrimônio Cultural Brasileiro", art),

                // ================= INGLÊS =================
                // Grammar
                new Assunto("Articles (Definite and Indefinite)", ing),
                new Assunto("Nouns (Plural, Countable/Uncountable)", ing),
                new Assunto("Pronouns (Personal, Possessive, Reflexive)", ing),
                new Assunto("Adjectives (Comparatives and Superlatives)", ing),
                new Assunto("Adverbs (Frequency, Manner, Place)", ing),
                new Assunto("Present Simple vs Present Continuous", ing),
                new Assunto("Past Simple vs Past Continuous", ing),
                new Assunto("Present Perfect vs Past Simple", ing),
                new Assunto("Present Perfect Continuous", ing),
                new Assunto("Past Perfect and Past Perfect Continuous", ing),
                new Assunto("Future Forms (Will, Going to, Present Continuous)", ing),
                new Assunto("Modal Verbs (Can, Could, May, Might, Must, Should)", ing),
                new Assunto("Passive Voice (All Tenses)", ing),
                new Assunto("Causative Form (Have/Get something done)", ing),
                new Assunto("Reported Speech (Statements and Questions)", ing),
                new Assunto("Conditionals (Zero, First, Second, Third)", ing),
                new Assunto("Mixed Conditionals", ing),
                new Assunto("Wishes and Regrets", ing),
                new Assunto("Relative Clauses (Who, Which, That, Whose)", ing),
                new Assunto("Question Tags", ing),
                new Assunto("Quantifiers (Some, Any, Much, Many, A lot)", ing),
                new Assunto("Prepositions (In, On, At - Time and Place)", ing),
                new Assunto("Phrasal Verbs (Common lists)", ing),
                new Assunto("Inversion (Hardly, Seldom, Not only)", ing),
                new Assunto("Gerunds vs Infinitives", ing),
                // Reading
                new Assunto("Reading Comprehension Strategies (Skimming/Scanning)", ing),
                new Assunto("Reference Words and Linking Words", ing),
                new Assunto("False Cognates (False Friends)", ing),
                new Assunto("Vocabulary: Idioms and Collocations", ing),

                // ================= HISTÓRIA =================
                // História Geral
                new Assunto("Pré-História: Paleolítico e Neolítico", hist),
                new Assunto("Antiguidade Oriental: Egito e Mesopotâmia", hist),
                new Assunto("Antiguidade Oriental: Hebreus, Fenícios e Persas", hist),
                new Assunto("Grécia Antiga: Períodos e Cidade-Estado", hist),
                new Assunto("Grécia: Atenas, Esparta e Cultura", hist),
                new Assunto("Roma Antiga: Monarquia e República", hist),
                new Assunto("Roma Antiga: Império e Decadência", hist),
                new Assunto("Alta Idade Média: Reinos Bárbaros e Império Bizantino", hist),
                new Assunto("Islamismo e Expansão Árabe", hist),
                new Assunto("Feudalismo: Sociedade e Economia", hist),
                new Assunto("Baixa Idade Média: Cruzadas e Renascimento Comercial", hist),
                new Assunto("Formação das Monarquias Nacionais", hist),
                new Assunto("Renascimento Cultural e Científico", hist),
                new Assunto("Reformas Religiosas (Protestante e Contrarreforma)", hist),
                new Assunto("Absolutismo Monárquico e Mercantilismo", hist),
                new Assunto("Iluminismo e Despotismo Esclarecido", hist),
                new Assunto("Independência dos EUA", hist),
                new Assunto("Revolução Francesa: Fases e Consequências", hist),
                new Assunto("Era Napoleônica e Congresso de Viena", hist),
                new Assunto("Revolução Industrial (1ª e 2ª)", hist),
                new Assunto("Movimentos Operários e Socialismo Séc XIX", hist),
                new Assunto("Unificações Tardia (Itália e Alemanha)", hist),
                new Assunto("Imperialismo e Neocolonialismo", hist),
                new Assunto("Primeira Guerra Mundial", hist),
                new Assunto("Revolução Russa de 1917", hist),
                new Assunto("Crise de 1929 e Grande Depressão", hist),
                new Assunto("Totalitarismos: Nazismo e Fascismo", hist),
                new Assunto("Segunda Guerra Mundial", hist),
                new Assunto("Guerra Fria: Conflitos e Corrida Armada", hist),
                new Assunto("Descolonização da Ásia e África", hist),
                new Assunto("Revolução Chinesa e Cubana", hist),
                new Assunto("Queda do Muro de Berlim e Fim da URSS", hist),
                new Assunto("Conflitos no Oriente Médio", hist),
                // História do Brasil
                new Assunto("Brasil Pré-Colonial e Indígenas", hist),
                new Assunto("Brasil Colônia: Capitanias e Governo Geral", hist),
                new Assunto("Economia Açucareira e Sociedade Colonial", hist),
                new Assunto("União Ibérica e Invasões Holandesas", hist),
                new Assunto("Expansão Territorial: Bandeiras e Tratados", hist),
                new Assunto("Ciclo do Ouro e Sociedade Mineradora", hist),
                new Assunto("Revoltas Nativistas e Separatistas", hist),
                new Assunto("Período Joanino (1808-1821)", hist),
                new Assunto("Processo de Independência", hist),
                new Assunto("Primeiro Reinado (D. Pedro I)", hist),
                new Assunto("Período Regencial e Revoltas", hist),
                new Assunto("Segundo Reinado: Política e Economia (Café)", hist),
                new Assunto("Segundo Reinado: Abolição e Imigração", hist),
                new Assunto("Guerra do Paraguai", hist),
                new Assunto("Crise do Império e Proclamação da República", hist),
                new Assunto("República da Espada", hist),
                new Assunto("República Oligárquica (Coronelismo)", hist),
                new Assunto("Revoltas da República Velha (Canudos, Vacina...)", hist),
                new Assunto("Tenentismo e Semana de 22", hist),
                new Assunto("Era Vargas: Gov. Provisório e Constitucional", hist),
                new Assunto("Era Vargas: Estado Novo", hist),
                new Assunto("República Populista (Dutra a Jango)", hist),
                new Assunto("Regime Militar: Castelo Branco a Médici", hist),
                new Assunto("Regime Militar: Geisel, Figueiredo e Abertura", hist),
                new Assunto("Nova República: Sarney a FHC", hist),
                new Assunto("Brasil Contemporâneo (Lula aos dias atuais)", hist),

                // ================= GEOGRAFIA =================
                // Geografia Física
                new Assunto("Astronomia Básica e Movimentos da Terra", geo),
                new Assunto("Cartografia: Coordenadas e Fusos Horários", geo),
                new Assunto("Cartografia: Escalas e Projeções", geo),
                new Assunto("Geologia: Estrutura Interna e Tipos de Rochas", geo),
                new Assunto("Tectônica de Placas e Deriva Continental", geo),
                new Assunto("Agentes Internos e Externos do Relevo", geo),
                new Assunto("Solos: Formação e Tipos", geo),
                new Assunto("Atmosfera e Elementos do Clima", geo),
                new Assunto("Fatores Climáticos e Tipos de Clima", geo),
                new Assunto("Fenômenos Climáticos (El Niño, Monções)", geo),
                new Assunto("Hidrografia: Ciclo da Água e Rios", geo),
                new Assunto("Bacias Hidrográficas do Mundo e Brasil", geo),
                new Assunto("Biomas Mundiais", geo),
                new Assunto("Domínios Morfoclimáticos do Brasil", geo),
                new Assunto("Problemas Ambientais (Aquecimento, Lixo, Água)", geo),
                // Geografia Humana e Econômica
                new Assunto("Demografia: Conceitos e Teorias", geo),
                new Assunto("Estrutura da População e Pirâmides Etárias", geo),
                new Assunto("Migrações Mundiais e Refugiados", geo),
                new Assunto("Urbanização: Conceitos e Hierarquia", geo),
                new Assunto("Problemas Urbanos e Segregação", geo),
                new Assunto("Agricultura: Sistemas e Revolução Verde", geo),
                new Assunto("Agropecuária no Brasil", geo),
                new Assunto("Recursos Minerais e Fontes de Energia Fóssil", geo),
                new Assunto("Fontes de Energia Renováveis", geo),
                new Assunto("Industrialização: Tipos e Modelos (Fordismo...)", geo),
                new Assunto("Industrialização Brasileira", geo),
                new Assunto("Transportes e Logística", geo),
                new Assunto("Comércio Mundial e Blocos Econômicos", geo),
                new Assunto("Globalização e Nova Ordem Mundial", geo),
                new Assunto("Geopolítica: Conflitos Atuais", geo),
                new Assunto("Geografia Regional do Brasil (Norte, NE, CO, SE, Sul)", geo),

                // ================= BIOLOGIA =================
                // Moléculas e Células
                new Assunto("Método Científico e Níveis de Organização", bio),
                new Assunto("Bioquímica: Água e Sais Minerais", bio),
                new Assunto("Bioquímica: Carboidratos e Lipídios", bio),
                new Assunto("Bioquímica: Proteínas e Enzimas", bio),
                new Assunto("Bioquímica: Ácidos Nucleicos (DNA e RNA)", bio),
                new Assunto("Citologia: Teoria Celular e Tipos de Células", bio),
                new Assunto("Membrana Plasmática e Transportes", bio),
                new Assunto("Citoplasma e Organelas", bio),
                new Assunto("Núcleo Celular e Cromossomos", bio),
                new Assunto("Divisão Celular: Ciclo Celular e Mitose", bio),
                new Assunto("Divisão Celular: Meiose e Gametogênese", bio),
                new Assunto("Síntese Proteica (Transcrição e Tradução)", bio),
                new Assunto("Metabolismo Energético: Fotossíntese", bio),
                new Assunto("Metabolismo Energético: Respiração e Fermentação", bio),
                // Seres Vivos
                new Assunto("Vírus: Estrutura e Reprodução", bio),
                new Assunto("Doenças Virais (Dengue, AIDS, Gripe...)", bio),
                new Assunto("Reino Monera: Bactérias e Doenças", bio),
                new Assunto("Reino Protista: Protozoários e Algas", bio),
                new Assunto("Doenças por Protozoários (Chagas, Malária...)", bio),
                new Assunto("Reino Fungi: Fungos e Importância", bio),
                new Assunto("Reino Plantae: Briófitas e Pteridófitas", bio),
                new Assunto("Reino Plantae: Gimnospermas e Angiospermas", bio),
                new Assunto("Fisiologia Vegetal (Hormônios, Transporte)", bio),
                new Assunto("Reino Animalia: Poríferos e Cnidários", bio),
                new Assunto("Reino Animalia: Platelmintos e Nematelmintos (Verminoses)", bio),
                new Assunto("Reino Animalia: Moluscos e Anelídeos", bio),
                new Assunto("Reino Animalia: Artrópodes e Equinodermos", bio),
                new Assunto("Reino Animalia: Peixes e Anfíbios", bio),
                new Assunto("Reino Animalia: Répteis, Aves e Mamíferos", bio),
                // Fisiologia Humana
                new Assunto("Sistema Digestório", bio),
                new Assunto("Sistema Respiratório", bio),
                new Assunto("Sistema Circulatório e Sangue", bio),
                new Assunto("Sistema Imunológico (Vacina e Soro)", bio),
                new Assunto("Sistema Excretor", bio),
                new Assunto("Sistema Nervoso", bio),
                new Assunto("Sistema Endócrino", bio),
                new Assunto("Sistema Reprodutor Humano", bio),
                // Genética e Evolução
                new Assunto("1ª Lei de Mendel", bio),
                new Assunto("Probabilidade em Genética e Heredogramas", bio),
                new Assunto("2ª Lei de Mendel", bio),
                new Assunto("Polialelia e Grupos Sanguíneos (ABO/Rh)", bio),
                new Assunto("Linkage e Mapeamento Genético", bio),
                new Assunto("Herança Sexual", bio),
                new Assunto("Mutações Cromossômicas", bio),
                new Assunto("Biotecnologia: Transgênicos e Clonagem", bio),
                new Assunto("Origem da Vida (Abiogênese vs Biogênese)", bio),
                new Assunto("Teorias Evolutivas: Lamarck e Darwin", bio),
                new Assunto("Teoria Sintética da Evolução (Neodarwinismo)", bio),
                new Assunto("Especiação", bio),
                // Ecologia
                new Assunto("Conceitos Básicos e Cadeias Alimentares", bio),
                new Assunto("Pirâmides Ecológicas e Produtividade", bio),
                new Assunto("Ciclos Biogeoquímicos (Água, Carbono, Nitrogênio)", bio),
                new Assunto("Relações Ecológicas (Intra e Interespecíficas)", bio),
                new Assunto("Sucessão Ecológica", bio),
                new Assunto("Dinâmica de Populações", bio),
                new Assunto("Desequilíbrios Ambientais e Poluição", bio),

                // ================= FILOSOFIA =================
                new Assunto("Surgimento da Filosofia e Mito vs Razão", fil),
                new Assunto("Pré-Socráticos: Arché e Physis", fil),
                new Assunto("Sofistas e a Retórica", fil),
                new Assunto("Sócrates: Maiêutica e Ironia", fil),
                new Assunto("Platão: Mundo das Ideias e Mito da Caverna", fil),
                new Assunto("Aristóteles: Metafísica, Ética e Política", fil),
                new Assunto("Helenismo (Estoicismo, Epicurismo...)", fil),
                new Assunto("Filosofia Medieval: Patrística (Santo Agostinho)", fil),
                new Assunto("Filosofia Medieval: Escolástica (São Tomás de Aquino)", fil),
                new Assunto("Renascimento e Revolução Científica", fil),
                new Assunto("Racionalismo (Descartes) vs Empirismo (Hume/Locke)", fil),
                new Assunto("Filosofia Política: Maquiavel", fil),
                new Assunto("Contratualistas: Hobbes, Locke e Rousseau", fil),
                new Assunto("Criticismo de Kant (Imperativo Categórico)", fil),
                new Assunto("Idealismo Alemão (Hegel)", fil),
                new Assunto("Materialismo Histórico (Marx)", fil),
                new Assunto("Positivismo (Comte)", fil),
                new Assunto("Vontade e Potência (Schopenhauer e Nietzsche)", fil),
                new Assunto("Existencialismo (Sartre e Camus)", fil),
                new Assunto("Escola de Frankfurt (Adorno, Horkheimer)", fil),
                new Assunto("Filosofia da Linguagem e Pós-Modernidade", fil),
                new Assunto("Bioética e Ética Contemporânea", fil),

                // ================= SOCIOLOGIA =================
                new Assunto("Surgimento da Sociologia e Contexto Histórico", soc),
                new Assunto("Émile Durkheim: Fato Social e Suicídio", soc),
                new Assunto("Max Weber: Ação Social e Burocracia", soc),
                new Assunto("Karl Marx: Luta de Classes e Mais-Valia", soc),
                new Assunto("Estratificação e Desigualdade Social", soc),
                new Assunto("Instituições Sociais (Família, Escola, Igreja)", soc),
                new Assunto("Cultura: Conceitos, Etnocentrismo e Relativismo", soc),
                new Assunto("Indústria Cultural e Cultura de Massa", soc),
                new Assunto("Ideologia e Alienação", soc),
                new Assunto("Poder, Política e Estado", soc),
                new Assunto("Democracia e Cidadania", soc),
                new Assunto("Movimentos Sociais (Antigos e Novos)", soc),
                new Assunto("Trabalho e Sociedade (Fordismo, Toyotismo)", soc),
                new Assunto("Violência e Criminalidade", soc),
                new Assunto("Sociologia Brasileira: Gilberto Freyre", soc),
                new Assunto("Sociologia Brasileira: Sérgio Buarque de Holanda", soc),
                new Assunto("Sociologia Brasileira: Caio Prado Jr.", soc),
                new Assunto("Questão Racial e de Gênero no Brasil", soc)
            );

            assuntoRepository.saveAll(listaAssuntos);
            System.out.println("--- 🚀 BANCO DEFINITIVO: TODAS AS MATÉRIAS E DETALHES CARREGADOS! ---");
        }
    }
}